upstream api {
    server bh-api:8080;
}

server {
    listen 80 default_server;
    server_name home.bharatbhusal.com localhost;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name home.bharatbhusal.com;

    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;

    location /api/ {
        proxy_pass http://api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
        add_header Cache-Control "no-cache";
    }
}
