name: Validate.Build.messages

on:
  push:
    branches: [develop]
    paths:
      - src/messages/**
  pull_request:
    branches: [develop]
    paths:
      - src/messages/**

jobs:
  messages:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/messages
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
